server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:

      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          tag:
          stream:
          image_name:
          container_name:
          image_id:
          container_id:
      - output:
          source: output
      - multiline:
          firstline: '\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}\,\d{3}'
          max_wait_time: 3s
          expression: '.*log.:(?P<log>[a-zA-Z]+).*stream.:(?P<stream>[T\d-:.Z]*).*attrs.:(?P<attrs>[a-zA-Z]+)'  

  - job_name: thingsboard
    static_configs:
      - targets:
          - localhost
        labels:
          job: thingsboard
          __path__: /var/log/thingsboard/*.log
    pipeline_stages:
      - multiline:
          firstline: '\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}\,\d{3}'
          max_wait_time: 3s
          

  
  - job_name: varlog1
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlog1
          __path__: /var/log/*log*
    pipeline_stages:
      - multiline:
          firstline: '^\[\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}\]'
          max_wait_time: 3s
